"""empty message

Revision ID: 06a73db65291
Revises: 4ab4b81bcf24
Create Date: 2020-06-21 12:57:32.127984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a73db65291'
down_revision = '4ab4b81bcf24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteers', sa.Column('email', sa.String(), nullable=True))
    op.execute('UPDATE volunteers SET email = \'johndoe@domain.com\' WHERE (email IS NULL) OR (email = \'\');')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteers', 'email')
    # ### end Alembic commands ###
