"""empty message

Revision ID: 8445702f07cd
Revises: 7965bb380b78
Create Date: 2020-06-18 18:26:08.981693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8445702f07cd'
down_revision = '7965bb380b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer', sa.Column('phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer', 'phone')
    # ### end Alembic commands ###
