"""empty message

Revision ID: b89c25deba46
Revises: 06a73db65291
Create Date: 2020-06-21 13:38:08.487567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89c25deba46'
down_revision = '06a73db65291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteers', sa.Column('gender', sa.Integer(), nullable=True))
    op.execute('UPDATE volunteers SET gender = 0 WHERE gender IS NULL;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteers', 'gender')
    # ### end Alembic commands ###
